/* eslint-disable @typescript-eslint/no-explicit-any */
import { useEffect, useState } from 'react'
import { Checkbox, Col, Divider, notification, Row } from 'antd'
import { LoadingOutlined } from '@ant-design/icons'
import pdfMake from 'pdfmake/build/pdfmake'
import pdfFonts from 'pdfmake/build/vfs_fonts'

pdfMake.vfs = pdfFonts.pdfMake.vfs

import {
  Button,
  ButtonsContainer,
  CheckboxContainer,
  CheckboxRow,
  Embed,
  Loader,
  PreviewObject,
  PreviewTitle,
} from './styles'
import { dd } from './example'

type TPDFDataListProps =
  | 'name'
  | 'birthdate'
  | 'age'
  | 'email'
  | 'primary_phone'
  | 'datetime'
  | 'updated_at'
  | 'last_appointment_datetime'
  | 'is_follow_up'
  | 'insurance_name'
  | 'payment_method'
  | 'exam_request'
  | 'notes'
  | 'signature_field'

interface ICheckboxOption {
  label: string
  value: TPDFDataListProps
}

interface IAppointmentDetailsDocumentProps {
  /** @default true */
  showPreview?: boolean
  /** @default true */
  autoGenerateDocument?: boolean
  /** @default true */
  showDownloadButton?: boolean
  /** @default false */
  showCreateButton?: boolean
}

const LoadingIcon = (
  <LoadingOutlined style={{ marginLeft: 10, fontSize: 16 }} spin />
)
const initialPDFDataList: TPDFDataListProps[] = [
  'name',
  'birthdate',
  'age',
  'email',
  'primary_phone',
  'datetime',
  'updated_at',
  'last_appointment_datetime',
  'is_follow_up',
  'insurance_name',
  'payment_method',
  'exam_request',
  'notes',
  'signature_field',
]
const checkboxOptions: ICheckboxOption[] = [
  { label: 'Nome do Paciente', value: 'name' },
  { label: 'Data de Nascimento', value: 'birthdate' },
  { label: 'Idade', value: 'age' },
  { label: 'E-mail', value: 'email' },
  { label: 'Telefone', value: 'primary_phone' },
  { label: 'Data da Consulta', value: 'datetime' },
  { label: 'Data da Última Atualização', value: 'updated_at' },
  { label: 'Data da Última Consulta', value: 'last_appointment_datetime' },
  { label: 'Retorno', value: 'is_follow_up' },
  { label: 'Convênio/Particular', value: 'insurance_name' },
  { label: 'Método de Pagamento', value: 'payment_method' },
  { label: 'Pedido de Exame(s)', value: 'exam_request' },
  { label: 'Anotações', value: 'notes' },
  { label: 'Linha de Assinatura (Médico)', value: 'signature_field' },
]

export const AppointmentDetailsDocument = ({
  showDownloadButton = true,
  showCreateButton = false,
  showPreview = true,
  autoGenerateDocument = true,
}: IAppointmentDetailsDocumentProps) => {
  const [PDFDataList, setPDFDataList] =
    useState<TPDFDataListProps[]>(initialPDFDataList)
  const [url, setUrl] = useState<string | null>(null)
  const [isLoading, setIsLoading] = useState(false)
  const docDefinition = dd

  const createPDF = () => {
    try {
      const pdfDocGenerator = pdfMake.createPdf(docDefinition as any)

      pdfDocGenerator.getBlob((blob) => {
        const url = URL.createObjectURL(blob)

        setUrl(url)
      })
    } catch (err) {
      notification.error({
        message:
          'Desculpe, mas ocorreu um erro ao gerar o arquivo PDF! Por favor, tente novamente mais tarde ou entre em contato!',
      })
    }
  }

  const downloadFile = () => {
    console.log('clicked to download the pdf file')
  }

  const getCreateDocumentBtnTitle = () => {
    if (isLoading) {
      return 'Aguarde o download do documento para poder gerar outro'
    }

    if (!PDFDataList?.length) {
      return 'Selecione pelo menos um campo para poder gerar um documento PDF'
    }

    return 'Clique para gerar um documento PDF com as informações desta consulta'
  }

  useEffect(() => {
    if (autoGenerateDocument) {
      createPDF()
    }
  }, [])

  useEffect(() => {
    return () => {
      if (url !== null) {
        URL.revokeObjectURL(url)
      }
    }
  }, [url])

  return (
    <>
      {checkboxOptions?.map(({ value, label }) => {
        const isChecked = PDFDataList.includes(value)

        return (
          <CheckboxContainer key={value}>
            <Row>
              <Col>
                <CheckboxRow>
                  <Col>
                    <Checkbox
                      onChange={() => {
                        const updatedDataList = isChecked
                          ? [...PDFDataList].filter((item) => item !== value)
                          : [...PDFDataList, value]

                        setPDFDataList(updatedDataList)

                        if (autoGenerateDocument) {
                          createPDF()
                        }
                      }}
                      value={isChecked}
                      checked={isChecked}>
                      {label}
                    </Checkbox>
                  </Col>
                </CheckboxRow>
              </Col>
            </Row>
          </CheckboxContainer>
        )
      })}

      {!!url && !!showPreview && (
        <>
          <Divider />
          <PreviewTitle>Prévia</PreviewTitle>
          <PreviewObject data={url} type="application/pdf">
            <Embed src={url} type="application/pdf" />
          </PreviewObject>
        </>
      )}

      {(!!showCreateButton || !!showDownloadButton) && (
        <ButtonsContainer>
          <Row gutter={12}>
            {!!showCreateButton && (
              <Col>
                <Button
                  type="button"
                  color="new"
                  title={getCreateDocumentBtnTitle()}
                  disabled={isLoading || !PDFDataList?.length}
                  onClick={createPDF}>
                  Gerar Documento
                </Button>
              </Col>
            )}

            {!!showDownloadButton && (
              <Col>
                <Button
                  type="button"
                  title={
                    url
                      ? 'Clique para baixar o arquivo PDF gerado'
                      : 'Você precisa primeiro gerar um arquivo PDF'
                  }
                  disabled={!url || isLoading}
                  onClick={downloadFile}>
                  {isLoading ? (
                    <>
                      Downloading
                      <Loader
                        indicator={LoadingIcon}
                        style={{ color: '#fff' }}
                      />
                    </>
                  ) : (
                    'Download'
                  )}
                </Button>
              </Col>
            )}
          </Row>
        </ButtonsContainer>
      )}
    </>
  )
}
